
package com.raiz;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RaizDaoImplService", targetNamespace = "http://raiz.com/", wsdlLocation = "http://localhost:2828/soap/raiz?wsdl")
public class RaizDaoImplService
    extends Service
{

    private final static URL RAIZDAOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RAIZDAOIMPLSERVICE_EXCEPTION;
    private final static QName RAIZDAOIMPLSERVICE_QNAME = new QName("http://raiz.com/", "RaizDaoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2828/soap/raiz?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RAIZDAOIMPLSERVICE_WSDL_LOCATION = url;
        RAIZDAOIMPLSERVICE_EXCEPTION = e;
    }

    public RaizDaoImplService() {
        super(__getWsdlLocation(), RAIZDAOIMPLSERVICE_QNAME);
    }

    public RaizDaoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RAIZDAOIMPLSERVICE_QNAME, features);
    }

    public RaizDaoImplService(URL wsdlLocation) {
        super(wsdlLocation, RAIZDAOIMPLSERVICE_QNAME);
    }

    public RaizDaoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RAIZDAOIMPLSERVICE_QNAME, features);
    }

    public RaizDaoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RaizDaoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RaizDao
     */
    @WebEndpoint(name = "RaizDaoImplPort")
    public RaizDao getRaizDaoImplPort() {
        return super.getPort(new QName("http://raiz.com/", "RaizDaoImplPort"), RaizDao.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RaizDao
     */
    @WebEndpoint(name = "RaizDaoImplPort")
    public RaizDao getRaizDaoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://raiz.com/", "RaizDaoImplPort"), RaizDao.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RAIZDAOIMPLSERVICE_EXCEPTION!= null) {
            throw RAIZDAOIMPLSERVICE_EXCEPTION;
        }
        return RAIZDAOIMPLSERVICE_WSDL_LOCATION;
    }

}
